language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"

before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-eslint' ]; then cd .. && eval "mv $currentfolder generator-eslint" && cd generator-eslint; fi
